# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.4
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: false
classname: HexMob
default_branch: main
description: A addon for Hex Casting adding serveral hex theme mobs.
display_name: Hex Mob
github_repo: HexMob
github_user: yggdyy_
homepage_url: https://yggdyy.github.io/HexMob
java_package: pub.pigeon.yggdyy.hexmob
kotlin_package: pub.pigeon.yggdyy.hexmob
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mit_license: true
mod_version: 0.0.1
modid: hexmob
sources_url: https://github.com/yggdyy/HexMob
